name: goreleaser

on:
  push:
    tags:
      - v*.*.*
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ^1
      upload_artifact:
        required: false
        type: boolean
        default: true
      lfs:
        required: false
        type: boolean
        default: false
        description: Whether to download Git-LFS files

concurrency:
  group: goreleaser
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: ${{ inputs.lfs }}
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 30
          name: dist
          path: |
            dist
